-- CATALOGO DE PAISES
Insert into cat_paises (cat_paises_id,clave,nombre) values (1,'AFG','Afghanistan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (2,'ALA','Aland islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (3,'ALB','Albania');
Insert into cat_paises (cat_paises_id,clave,nombre) values (4,'DZA','Algeria');
Insert into cat_paises (cat_paises_id,clave,nombre) values (5,'ASM','American samoa');
Insert into cat_paises (cat_paises_id,clave,nombre) values (6,'AND','Andorra');
Insert into cat_paises (cat_paises_id,clave,nombre) values (7,'AGO','Angola');
Insert into cat_paises (cat_paises_id,clave,nombre) values (8,'AIA','Anguilla');
Insert into cat_paises (cat_paises_id,clave,nombre) values (9,'ATA','Antarctica');
Insert into cat_paises (cat_paises_id,clave,nombre) values (10,'ATG','Antigua and barbuda');
Insert into cat_paises (cat_paises_id,clave,nombre) values (11,'ARG','Argentina');
Insert into cat_paises (cat_paises_id,clave,nombre) values (12,'ARM','Armenia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (13,'ABW','Aruba');
Insert into cat_paises (cat_paises_id,clave,nombre) values (14,'AUS','Australia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (15,'AUT','Austria');
Insert into cat_paises (cat_paises_id,clave,nombre) values (16,'AZE','Azerbaijan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (17,'BHS','Bahamas');
Insert into cat_paises (cat_paises_id,clave,nombre) values (18,'BHR','Bahrain');
Insert into cat_paises (cat_paises_id,clave,nombre) values (19,'BGD','Bangladesh');
Insert into cat_paises (cat_paises_id,clave,nombre) values (20,'BRB','Barbados');
Insert into cat_paises (cat_paises_id,clave,nombre) values (21,'BLR','Belarus');
Insert into cat_paises (cat_paises_id,clave,nombre) values (22,'BEL','Belgium');
Insert into cat_paises (cat_paises_id,clave,nombre) values (23,'BLZ','Belize');
Insert into cat_paises (cat_paises_id,clave,nombre) values (24,'BEN','Benin');
Insert into cat_paises (cat_paises_id,clave,nombre) values (25,'BMU','Bermuda');
Insert into cat_paises (cat_paises_id,clave,nombre) values (26,'BTN','Bhutan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (27,'BOL','Bolivia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (28,'BIH','Bosnia and herzegovina');
Insert into cat_paises (cat_paises_id,clave,nombre) values (29,'BWA','Botswana');
Insert into cat_paises (cat_paises_id,clave,nombre) values (30,'BVT','Bouvet island');
Insert into cat_paises (cat_paises_id,clave,nombre) values (31,'BRA','Brazil');
Insert into cat_paises (cat_paises_id,clave,nombre) values (32,'VGB','British virgin islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (33,'IOT','British indian ocean territory');
Insert into cat_paises (cat_paises_id,clave,nombre) values (34,'BRN','Brunei darussalam');
Insert into cat_paises (cat_paises_id,clave,nombre) values (35,'BGR','Bulgaria');
Insert into cat_paises (cat_paises_id,clave,nombre) values (36,'BFA','Burkina faso');
Insert into cat_paises (cat_paises_id,clave,nombre) values (37,'BDI','Burundi');
Insert into cat_paises (cat_paises_id,clave,nombre) values (38,'KHM','Cambodia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (39,'CMR','Cameroon');
Insert into cat_paises (cat_paises_id,clave,nombre) values (40,'CAN','Canada');
Insert into cat_paises (cat_paises_id,clave,nombre) values (41,'CPV','Cape verde');
Insert into cat_paises (cat_paises_id,clave,nombre) values (42,'CYM','Cayman islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (43,'CAF','Central african republic');
Insert into cat_paises (cat_paises_id,clave,nombre) values (44,'TCD','Chad');
Insert into cat_paises (cat_paises_id,clave,nombre) values (45,'CHL','Chile');
Insert into cat_paises (cat_paises_id,clave,nombre) values (46,'CHN','China');
Insert into cat_paises (cat_paises_id,clave,nombre) values (47,'HKG','Hong kong, special administrative region of china');
Insert into cat_paises (cat_paises_id,clave,nombre) values (48,'MAC','Macao, special administrative region of china');
Insert into cat_paises (cat_paises_id,clave,nombre) values (49,'CXR','Christmas island');
Insert into cat_paises (cat_paises_id,clave,nombre) values (50,'CCK','Cocos (keeling) islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (51,'COL','Colombia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (52,'COM','Comoros');
Insert into cat_paises (cat_paises_id,clave,nombre) values (53,'COG','Congo (brazzaville)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (54,'COD','Congo, democratic republic of the');
Insert into cat_paises (cat_paises_id,clave,nombre) values (55,'COK','Cook islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (56,'CRI','Costa rica');
Insert into cat_paises (cat_paises_id,clave,nombre) values (57,'CIV','Côte d''ivoire');
Insert into cat_paises (cat_paises_id,clave,nombre) values (58,'HRV','Croatia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (59,'CUB','Cuba');
Insert into cat_paises (cat_paises_id,clave,nombre) values (60,'CYP','Cyprus');
Insert into cat_paises (cat_paises_id,clave,nombre) values (61,'CZE','Czech republic');
Insert into cat_paises (cat_paises_id,clave,nombre) values (62,'DNK','Denmark');
Insert into cat_paises (cat_paises_id,clave,nombre) values (63,'DJI','Djibouti');
Insert into cat_paises (cat_paises_id,clave,nombre) values (64,'DMA','Dominica');
Insert into cat_paises (cat_paises_id,clave,nombre) values (65,'DOM','Dominican republic');
Insert into cat_paises (cat_paises_id,clave,nombre) values (66,'ECU','Ecuador');
Insert into cat_paises (cat_paises_id,clave,nombre) values (67,'EGY','Egypt');
Insert into cat_paises (cat_paises_id,clave,nombre) values (68,'SLV','El salvador');
Insert into cat_paises (cat_paises_id,clave,nombre) values (69,'GNQ','Equatorial guinea');
Insert into cat_paises (cat_paises_id,clave,nombre) values (70,'ERI','Eritrea');
Insert into cat_paises (cat_paises_id,clave,nombre) values (71,'EST','Estonia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (72,'ETH','Ethiopia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (73,'FLK','Falkland islands (malvinas)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (74,'FRO','Faroe islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (75,'FJI','Fiji');
Insert into cat_paises (cat_paises_id,clave,nombre) values (76,'FIN','Finland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (77,'FRA','France');
Insert into cat_paises (cat_paises_id,clave,nombre) values (78,'GUF','French guiana');
Insert into cat_paises (cat_paises_id,clave,nombre) values (79,'PYF','French polynesia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (80,'ATF','French southern territories');
Insert into cat_paises (cat_paises_id,clave,nombre) values (81,'GAB','Gabon');
Insert into cat_paises (cat_paises_id,clave,nombre) values (82,'GMB','Gambia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (83,'GEO','Georgia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (84,'DEU','Germany');
Insert into cat_paises (cat_paises_id,clave,nombre) values (85,'GHA','Ghana');
Insert into cat_paises (cat_paises_id,clave,nombre) values (86,'GIB','Gibraltar');
Insert into cat_paises (cat_paises_id,clave,nombre) values (87,'GRC','Greece');
Insert into cat_paises (cat_paises_id,clave,nombre) values (88,'GRL','Greenland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (89,'GRD','Grenada');
Insert into cat_paises (cat_paises_id,clave,nombre) values (90,'GLP','Guadeloupe');
Insert into cat_paises (cat_paises_id,clave,nombre) values (91,'GUM','Guam');
Insert into cat_paises (cat_paises_id,clave,nombre) values (92,'GTM','Guatemala');
Insert into cat_paises (cat_paises_id,clave,nombre) values (93,'GGY','Guernsey');
Insert into cat_paises (cat_paises_id,clave,nombre) values (94,'GIN','Guinea');
Insert into cat_paises (cat_paises_id,clave,nombre) values (95,'GNB','Guinea-bissau');
Insert into cat_paises (cat_paises_id,clave,nombre) values (96,'GUY','Guyana');
Insert into cat_paises (cat_paises_id,clave,nombre) values (97,'HTI','Haiti');
Insert into cat_paises (cat_paises_id,clave,nombre) values (98,'HMD','Heard island and mcdonald islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (99,'VAT','Holy see (vatican city state)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (100,'HND','Honduras');
Insert into cat_paises (cat_paises_id,clave,nombre) values (101,'HUN','Hungary');
Insert into cat_paises (cat_paises_id,clave,nombre) values (102,'ISL','Iceland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (103,'IND','India');
Insert into cat_paises (cat_paises_id,clave,nombre) values (104,'IDN','Indonesia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (105,'IRN','Iran, islamic republic of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (106,'IRQ','Iraq');
Insert into cat_paises (cat_paises_id,clave,nombre) values (107,'IRL','Ireland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (108,'IMN','Isle of man');
Insert into cat_paises (cat_paises_id,clave,nombre) values (109,'ISR','Israel');
Insert into cat_paises (cat_paises_id,clave,nombre) values (110,'ITA','Italy');
Insert into cat_paises (cat_paises_id,clave,nombre) values (111,'JAM','Jamaica');
Insert into cat_paises (cat_paises_id,clave,nombre) values (112,'JPN','Japan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (113,'JEY','Jersey');
Insert into cat_paises (cat_paises_id,clave,nombre) values (114,'JOR','Jordan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (115,'KAZ','Kazakhstan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (116,'KEN','Kenya');
Insert into cat_paises (cat_paises_id,clave,nombre) values (117,'KIR','Kiribati');
Insert into cat_paises (cat_paises_id,clave,nombre) values (118,'PRK','Korea, democratic people''s republic of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (119,'KOR','Korea, republic of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (120,'KWT','Kuwait');
Insert into cat_paises (cat_paises_id,clave,nombre) values (121,'KGZ','Kyrgyzstan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (122,'LAO','Lao pdr');
Insert into cat_paises (cat_paises_id,clave,nombre) values (123,'LVA','Latvia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (124,'LBN','Lebanon');
Insert into cat_paises (cat_paises_id,clave,nombre) values (125,'LSO','Lesotho');
Insert into cat_paises (cat_paises_id,clave,nombre) values (126,'LBR','Liberia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (127,'LBY','Libya');
Insert into cat_paises (cat_paises_id,clave,nombre) values (128,'LIE','Liechtenstein');
Insert into cat_paises (cat_paises_id,clave,nombre) values (129,'LTU','Lithuania');
Insert into cat_paises (cat_paises_id,clave,nombre) values (130,'LUX','Luxembourg');
Insert into cat_paises (cat_paises_id,clave,nombre) values (131,'MKD','Macedonia, republic of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (132,'MDG','Madagascar');
Insert into cat_paises (cat_paises_id,clave,nombre) values (133,'MWI','Malawi');
Insert into cat_paises (cat_paises_id,clave,nombre) values (134,'MYS','Malaysia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (135,'MDV','Maldives');
Insert into cat_paises (cat_paises_id,clave,nombre) values (136,'MLI','Mali');
Insert into cat_paises (cat_paises_id,clave,nombre) values (137,'MLT','Malta');
Insert into cat_paises (cat_paises_id,clave,nombre) values (138,'MHL','Marshall islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (139,'MTQ','Martinique');
Insert into cat_paises (cat_paises_id,clave,nombre) values (140,'MRT','Mauritania');
Insert into cat_paises (cat_paises_id,clave,nombre) values (141,'MUS','Mauritius');
Insert into cat_paises (cat_paises_id,clave,nombre) values (142,'MYT','Mayotte');
Insert into cat_paises (cat_paises_id,clave,nombre) values (143,'MEX','México');
Insert into cat_paises (cat_paises_id,clave,nombre) values (144,'FSM','Micronesia, federated states of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (145,'MDA','Moldova');
Insert into cat_paises (cat_paises_id,clave,nombre) values (146,'MCO','Monaco');
Insert into cat_paises (cat_paises_id,clave,nombre) values (147,'MNG','Mongolia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (148,'MNE','Montenegro');
Insert into cat_paises (cat_paises_id,clave,nombre) values (149,'MSR','Montserrat');
Insert into cat_paises (cat_paises_id,clave,nombre) values (150,'MAR','Morocco');
Insert into cat_paises (cat_paises_id,clave,nombre) values (151,'MOZ','Mozambique');
Insert into cat_paises (cat_paises_id,clave,nombre) values (152,'MMR','Myanmar');
Insert into cat_paises (cat_paises_id,clave,nombre) values (153,'NAM','Namibia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (154,'NRU','Nauru');
Insert into cat_paises (cat_paises_id,clave,nombre) values (155,'NPL','Nepal');
Insert into cat_paises (cat_paises_id,clave,nombre) values (156,'NLD','Netherlands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (157,'ANT','Netherlands antilles');
Insert into cat_paises (cat_paises_id,clave,nombre) values (158,'NCL','New caledonia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (159,'NZL','New zealand');
Insert into cat_paises (cat_paises_id,clave,nombre) values (160,'NIC','Nicaragua');
Insert into cat_paises (cat_paises_id,clave,nombre) values (161,'NER','Niger');
Insert into cat_paises (cat_paises_id,clave,nombre) values (162,'NGA','Nigeria');
Insert into cat_paises (cat_paises_id,clave,nombre) values (163,'NIU','Niue');
Insert into cat_paises (cat_paises_id,clave,nombre) values (164,'NFK','Norfolk island');
Insert into cat_paises (cat_paises_id,clave,nombre) values (165,'MNP','Northern mariana islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (166,'NOR','Norway');
Insert into cat_paises (cat_paises_id,clave,nombre) values (167,'OMN','Oman');
Insert into cat_paises (cat_paises_id,clave,nombre) values (168,'PAK','Pakistan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (169,'PLW','Palau');
Insert into cat_paises (cat_paises_id,clave,nombre) values (170,'PSE','Palestinian territory, occupied');
Insert into cat_paises (cat_paises_id,clave,nombre) values (171,'PAN','Panama');
Insert into cat_paises (cat_paises_id,clave,nombre) values (172,'PNG','Papua new guinea');
Insert into cat_paises (cat_paises_id,clave,nombre) values (173,'PRY','Paraguay');
Insert into cat_paises (cat_paises_id,clave,nombre) values (174,'PER','Peru');
Insert into cat_paises (cat_paises_id,clave,nombre) values (175,'PHL','Philippines');
Insert into cat_paises (cat_paises_id,clave,nombre) values (176,'PCN','Pitcairn');
Insert into cat_paises (cat_paises_id,clave,nombre) values (177,'POL','Poland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (178,'PRT','Portugal');
Insert into cat_paises (cat_paises_id,clave,nombre) values (179,'PRI','Puerto rico');
Insert into cat_paises (cat_paises_id,clave,nombre) values (180,'QAT','Qatar');
Insert into cat_paises (cat_paises_id,clave,nombre) values (181,'REU','Réunion');
Insert into cat_paises (cat_paises_id,clave,nombre) values (182,'ROU','Romania');
Insert into cat_paises (cat_paises_id,clave,nombre) values (183,'RUS','Russian federation');
Insert into cat_paises (cat_paises_id,clave,nombre) values (184,'RWA','Rwanda');
Insert into cat_paises (cat_paises_id,clave,nombre) values (185,'BLM','Saint-barthélemy');
Insert into cat_paises (cat_paises_id,clave,nombre) values (186,'SHN','Saint helena');
Insert into cat_paises (cat_paises_id,clave,nombre) values (187,'KNA','Saint kitts and nevis');
Insert into cat_paises (cat_paises_id,clave,nombre) values (188,'LCA','Saint lucia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (189,'MAF','Saint-martin (french part)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (190,'SPM','Saint pierre and miquelon');
Insert into cat_paises (cat_paises_id,clave,nombre) values (191,'VCT','Saint vincent and grenadines');
Insert into cat_paises (cat_paises_id,clave,nombre) values (192,'WSM','Samoa');
Insert into cat_paises (cat_paises_id,clave,nombre) values (193,'SMR','San marino');
Insert into cat_paises (cat_paises_id,clave,nombre) values (194,'STP','Sao tome and principe');
Insert into cat_paises (cat_paises_id,clave,nombre) values (195,'SAU','Saudi arabia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (196,'SEN','Senegal');
Insert into cat_paises (cat_paises_id,clave,nombre) values (197,'SRB','Serbia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (198,'SYC','Seychelles');
Insert into cat_paises (cat_paises_id,clave,nombre) values (199,'SLE','Sierra leone');
Insert into cat_paises (cat_paises_id,clave,nombre) values (200,'SGP','Singapore');
Insert into cat_paises (cat_paises_id,clave,nombre) values (201,'SVK','Slovakia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (202,'SVN','Slovenia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (203,'SLB','Solomon islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (204,'SOM','Somalia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (205,'ZAF','South africa');
Insert into cat_paises (cat_paises_id,clave,nombre) values (206,'SGS','South georgia and the south sandwich islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (207,'SSD','South sudan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (208,'ESP','Spain');
Insert into cat_paises (cat_paises_id,clave,nombre) values (209,'LKA','Sri lanka');
Insert into cat_paises (cat_paises_id,clave,nombre) values (210,'SDN','Sudan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (211,'SUR','Suriname *');
Insert into cat_paises (cat_paises_id,clave,nombre) values (212,'SJM','Svalbard and jan mayen islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (213,'SWZ','Swaziland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (214,'SWE','Sweden');
Insert into cat_paises (cat_paises_id,clave,nombre) values (215,'CHE','Switzerland');
Insert into cat_paises (cat_paises_id,clave,nombre) values (216,'SYR','Syrian arab republic (syria)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (217,'TWN','Taiwan, republic of china');
Insert into cat_paises (cat_paises_id,clave,nombre) values (218,'TJK','Tajikistan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (219,'TZA','Tanzania *, united republic of');
Insert into cat_paises (cat_paises_id,clave,nombre) values (220,'THA','Thailand');
Insert into cat_paises (cat_paises_id,clave,nombre) values (221,'TLS','Timor-leste');
Insert into cat_paises (cat_paises_id,clave,nombre) values (222,'TGO','Togo');
Insert into cat_paises (cat_paises_id,clave,nombre) values (223,'TKL','Tokelau');
Insert into cat_paises (cat_paises_id,clave,nombre) values (224,'TON','Tonga');
Insert into cat_paises (cat_paises_id,clave,nombre) values (225,'TTO','Trinidad and tobago');
Insert into cat_paises (cat_paises_id,clave,nombre) values (226,'TUN','Tunisia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (227,'TUR','Turkey');
Insert into cat_paises (cat_paises_id,clave,nombre) values (228,'TKM','Turkmenistan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (229,'TCA','Turks and caicos islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (230,'TUV','Tuvalu');
Insert into cat_paises (cat_paises_id,clave,nombre) values (231,'UGA','Uganda');
Insert into cat_paises (cat_paises_id,clave,nombre) values (232,'UKR','Ukraine');
Insert into cat_paises (cat_paises_id,clave,nombre) values (233,'ARE','United arab emirates');
Insert into cat_paises (cat_paises_id,clave,nombre) values (234,'GBR','United kingdom');
Insert into cat_paises (cat_paises_id,clave,nombre) values (235,'USA','United states of america');
Insert into cat_paises (cat_paises_id,clave,nombre) values (236,'UMI','United states minor outlying islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (237,'URY','Uruguay');
Insert into cat_paises (cat_paises_id,clave,nombre) values (238,'UZB','Uzbekistan');
Insert into cat_paises (cat_paises_id,clave,nombre) values (239,'VUT','Vanuatu');
Insert into cat_paises (cat_paises_id,clave,nombre) values (240,'VEN','Venezuela (bolivarian republic of)');
Insert into cat_paises (cat_paises_id,clave,nombre) values (241,'VNM','Viet nam');
Insert into cat_paises (cat_paises_id,clave,nombre) values (242,'VIR','Virgin islands, us');
Insert into cat_paises (cat_paises_id,clave,nombre) values (243,'WLF','Wallis and futuna islands');
Insert into cat_paises (cat_paises_id,clave,nombre) values (244,'ESH','Western sahara');
Insert into cat_paises (cat_paises_id,clave,nombre) values (245,'YEM','Yemen');
Insert into cat_paises (cat_paises_id,clave,nombre) values (246,'ZMB','Zambia');
Insert into cat_paises (cat_paises_id,clave,nombre) values (247,'ZWE','Zimbabwe');